version: "3.8"

services:
  backend-service:
    build:
      context: ./backend

      dockerfile: Dockerfile

    environment:
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}

  frontend-service:
    build:
      context: ./frontend
      dockerfile: Dockerfile

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: always
    depends_on:
      - frontend-service
      - backend-service

volumes:
  caddy_data:
  caddy_config:
