name: Monorepo CI (TypeScript Linting)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  lint-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install Frontend Dependencies
        run: npm ci --prefix frontend --legacy-peer-deps

      - name: Install Backend Dependencies
        run: npm ci --prefix backend

      #  Kör lint i varje mapp för sig!
      - name: Run ESLint on Frontend
        run: npm run lint --prefix frontend

      - name: Run ESLint on Backend
        run: npm run lint --prefix backend
